### ISSUE TITLE
Version 0.6 not pushed to GitHub?

### ISSUE THREAD

**Issue by adamchainz** [robertkovac/django-fieldsets-with-inlines#1]
I see a new version 7 hours ago, but no corresponding commits on GitHub - 
https://pypi.org/project/django-fieldsets-with-inlines/#history

Did you forget to push? :)

**Comment by robertkovac** [comment]
I really was :(
The beauty of manual deployment.

It is pushed now

**Comment by adamchainz** [comment]
👍 Thanks. Was researching this library for a project, looks pretty useful!
